name: Deploy Frontend

on:
  push:
    branches: [ main ] # Se déclenche lors d'un push sur main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'

      - name: Generate env file
        run: |
          cat <<'EOF' > .env
          VITE_API_URL=${{ secrets.VITE_API_URL }}
          VITE_ACSDLE_CRYPTO_KEY=${{ secrets.VITE_ACSDLE_CRYPTO_KEY }}
          EOF

      - name: Run remote command
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          script: |
            cd /var/www/acsv2/frontend
            git pull origin main

      - name: Install & Build
        run: |
          npm install
          npm run build  # Génère le dossier dist/

      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          port: 22
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}   # ou ssh_private_key
          sftp_only: true
          local_path: ./dist
          remote_path: /var/www/acsv2/frontend/dist
          delete_remote_files: true
          sftpArgs: "-o StrictHostKeyChecking=no"
          ssh_private_key: ""